# Generated by Django 4.2.7 on 2023-11-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('DeptoId', models.IntegerField(primary_key=True, serialize=False)),
                ('DeptoNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='puestos',
            fields=[
                ('PuestoId', models.BigAutoField(primary_key=True, serialize=False)),
                ('PuestoNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('DeptoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.departamentos')),
                ('puestoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.puestos')),
            ],
        ),
    ]
