# Generated by Django 5.0 on 2023-12-14 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='identidad',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='el id debe tener 13 digitos', regex='^[0-9]{13}$'), django.core.validators.MinLengthValidator(0, message='El ID debe ser un valor numérico positivo'), django.core.validators.MinLengthValidator(13, message='El ID no debe superar los 13 dígitos')]),
        ),
    ]
